### ISSUE TITLE
Updating packages

### ISSUE THREAD

**Issue by zEEmperon** [radacovsky/ngrx-store-idb#3]
Could you please update some packages? In particular @angular/common :))

**Comment by radacovsky** [comment]
Hi @zEEmperon I have published version 1.1.2 with Angular peer dependencies bumped to v13. Please try it out and close the issue if all is ok.

**Comment by zEEmperon** [comment]
@radacovsky Hi, thanks a lot for respond and update :)
This package is very helpful, great and easy to use

But there is another issue: my project uses angular 11 (~11.2.12 is specified in package.json), but now your module uses angular 13 (^13.3.0 specified in package.json). So, the question is: is there a way to provide back compatibility?:)

**Comment by radacovsky** [comment]
Hi @zEEmperon .
I update to v13 because there was breaking change from this version on in the way how Angular packages are built(has to do with ViewEngine vs Ivy renderer). If you use older Angular version you should be fine using version 1.1.1 and ignore warnings.

**Comment by zEEmperon** [comment]
@radacovsky thanks a lot!) 
I will consider the way to migrate my project to newer version of angular)
I will close the issue. Have a nice day. You have done a great work: your project is excellent:)
