### ISSUE TITLE
Uncaught TypeError: (deepmerge__WEBPACK_IMPORTED_MODULE_0___namespace_cache || deepmerge__WEBPACK_IMPORTED_MODULE_0___namespace_cache) is not a function

### ISSUE THREAD

**Issue by nwatrailhub** [radacovsky/ngrx-store-idb#4]
When attempting to set up the library I am getting this error: 
Uncaught TypeError: (deepmerge__WEBPACK_IMPORTED_MODULE_0___namespace_cache || deepmerge__WEBPACK_IMPORTED_MODULE_0___namespace_cache) is not a function

**Comment by couchlab-pl** [comment]
it's connected with webback module import / export. Fix is to change in node_modules/ngrx-store-idb/fesm2020/ngrx-store-idb 
from 
import * as deepmerge from 'deepmerge';
to 
import deepmerge from 'deepmerge';

hope author will fix it also

**Comment by mmjr-x** [comment]
@radacovsky any update on this? :)

**Comment by couchlab-pl** [comment]
Hi, 

As I said it is working with that patch - so it will be great to update library
