### ISSUE TITLE
Incompatible with altest Angular: v14

### ISSUE THREAD

**Issue by istvan-panczel** [radacovsky/ngrx-store-idb#5]
Hi,

Can you please bump up the versions once again for Angular v14?

**Comment by mrlldd** [comment]
@radacovsky sure
well, I have not worked with npm packages ever but I'll try my best :)

**Comment by mamay12** [comment]
@radacovsky hello, can you please check PR with upgrade to angular v14 asap? I want to upgrade it to angular v15 today :)

**Comment by radacovsky** [comment]
Thanks for the PR. I am not able to test if it works but the build passes. It has been merged and I will soon publish it in npm

**Comment by radacovsky** [comment]
Version 1.1.3 published. Can someone test if it works?

**Comment by mamay12** [comment]
@radacovsky we will test it in our project after version 1.1.4 will be published, i created PR

**Comment by radacovsky** [comment]
Version 1.1.4 published in npm. Let me know if it works so we can close this issue. Thanks for help

**Comment by mamay12** [comment]
just tested it, it doesn't work. fails in metareducer (line 272) with error "(deepmerge__WEBPACK_IMPORTED_MODULE_0___namespace_cache || deepmerge__WEBPACK_IMPORTED_MODULE_0___namespace_cache) is not a function"
Im looking for solving

**Comment by mrlldd** [comment]
@radacovsky I have created PR (also related to #4) with possible fix of deepmerge import, if it'll work - those changes should be reflected for Angular v14 I believe

**Comment by mamay12** [comment]
@radacovsky Hello, any updates here?

**Comment by mrlldd** [comment]
@radacovsky I haven't tested it yet, I'll do it asap

**Comment by radacovsky** [comment]
I have published v14 and v15 versions. Fingers crossed, I hope it works now. Let me know, please so that I can close this issue.

**Comment by mamay12** [comment]
@radacovsky works fine, you can close this issue :)
